### ISSUE TITLE
cardinalcommerceprod.jfrog.io server not response

### ISSUE THREAD

**Issue by sidhu-patil** [harrowmykel/flutter_paypal_native#13]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2.
     Required by:
         project :app > com.paypal.checkout:android-sdk:0.8.8
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2.
         > Could not get resource 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom'.
            > Could not GET 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom'.
               > cardinalcommerceprod.jfrog.io

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 52s

**Comment by harrowmykel** [comment]
Fixed in latest version. Will be live in a few hours

**Comment by sidhu-patil** [comment]
noops, this problem also occurs in your lastest version 


Retrying Gradle Build: #2, wait time: 200ms
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2.
     Required by:
         project :app > project :flutter_paypal_native > com.paypal.checkout:android-sdk:0.8.8
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2.
         > Could not get resource 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom'.
            > Could not GET 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom'.
               > cardinalcommerceprod.jfrog.io

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 47s
