### ISSUE TITLE
IOS: Pay Now button is only loading animation

### ISSUE THREAD

**Issue by Philnue** [harrowmykel/flutter_paypal_native#16]
I made all changes like you did. And implemented the trouble shooting. 
When I wait some seconds I can press on the blue button, even it is still loading but the payments goes through

**Comment by harrowmykel** [comment]
Will check now

**Comment by Philnue** [comment]
Thank you man :D

**Comment by Philnue** [comment]
@harrowmykel you checked it ?

**Comment by harrowmykel** [comment]
Yes, You have to press the button twice. The bug  is from paypal. Sorry for the late response

**Comment by harrowmykel** [comment]
New version is now available. Please use  v1. 0.1

**Comment by Philnue** [comment]
Is Fixed now, I see the price. With Blue background :D
