### ISSUE TITLE
noops, this problem also occurs in your lastest version

### ISSUE THREAD

**Issue by sidhu-patil** [harrowmykel/flutter_paypal_native#17]
noops, this problem also occurs in your lastest version 

Retrying Gradle Build: #2, wait time: 200ms
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2.
     Required by:
         project :app > project :flutter_paypal_native > com.paypal.checkout:android-sdk:0.8.8
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.7-2.
         > Could not get resource 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom'.
            > Could not GET 'https://cardinalcommerceprod.jfrog.io/artifactory/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.7-2/cardinalmobilesdk-2.2.7-2.pom'.
               > cardinalcommerceprod.jfrog.io

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 47s

_Originally posted by @sidhu-patil in https://github.com/harrowmykel/flutter_paypal_native/issues/13#issuecomment-1542701483_

**Comment by sidhu-patil** [comment]
I fixed this problem.... This problem occurs in my case because of cardinalcommerceprod.frog.io is not access in India... I connect with us vpn and problem fixed 😅😅

**Comment by harrowmykel** [comment]
perfect There is a new version now
