### ISSUE TITLE
Android SDK issues

### ISSUE THREAD

**Issue by rikirrulla** [harrowmykel/flutter_paypal_native#29]
Flagged non-compliance with Google Play policies for SDK com.paypal.android.sdk:data-collector:3.20.0. 

<img width="778" alt="Screenshot 2023-12-09 at 2 45 16 AM" src="https://github.com/harrowmykel/flutter_paypal_native/assets/45070870/4082ca71-f4d1-4643-937f-d8ce2813df27">

**Comment by ehangwork** [comment]
The same problem！

**Comment by vitorpegas95** [comment]
Yeah, getting the same warning. Any guesses how we can fix it?

**Comment by harrowmykel** [comment]
I will work on this this evening and push a new update


Sorry for the inconvenience

**Comment by vitorpegas95** [comment]
> I will work on this this evening and push a new update
> 
> Sorry for the inconvenience

No problem, thank you so much for your work!! <3 Take your time ^^

**Comment by harrowmykel** [comment]
Please try the new version 2.1.0


Also kindly note this package has been marked deprecated by PayPal and now only in maintenance mode.
