### ISSUE TITLE
Invalid scope with Sandbox environment in Android

### ISSUE THREAD

**Issue by nayanAubie** [harrowmykel/flutter_paypal_native#3]
For the Android platform, I followed the steps mentioned at [flutter_paypal_native](https://pub.dev/packages/flutter_paypal_native) for the Android 
Used version => `flutter_paypal_native: ^0.0.6`

It works fine on iOS but not working in Android. I am using the Sandbox environment on both platforms.

![Error Image](https://user-images.githubusercontent.com/109264909/206110099-d6b29063-5bc8-4f3d-893f-194e73a2a165.jpg)

**Comment by harrowmykel** [comment]
Hey Nayan, Thanks for opening the issue. 

I have checked this does not seem to be a problem from the android sdk

Check out this links

https://stackoverflow.com/questions/68114328/paypal-native-checkout-sdkandroid-invalid-scope

https://stackoverflow.com/questions/68461486/paypal-android-checkout-sdk-gives-invalid-scope-in-live-mode
