### ISSUE TITLE
Can't run on IOS

### ISSUE THREAD

**Issue by juhaodong** [harrowmykel/flutter_paypal_native#4]
Swift Compiler Error (Xcode): Cannot infer return type for closure with multiple statements; add explicit type to disambiguate
flutter_paypal_native-0.0.6/ios/Classes/helpers/PayPalCallBackHelper.swift:56:40

**Comment by harrowmykel** [comment]
Hi @tgloc96, could you please have a look at this? :)

**Comment by juhaodong** [comment]
I delete some code in the cache files, it works. but it shouldn't be like this way I think.
