### ISSUE TITLE
com.paypal.checkout.merchanttoken.CreateLsatTokenException: Unable to create the LSAT Token for the given Client ID

### ISSUE THREAD

**Issue by korolzhang** [harrowmykel/flutter_paypal_native#5]
_flutterPayPalPlugin.init(
    returnUrl: payPalRuturnUrl,
    clientID: payPalClientID,
    payPalEnvironment: FPayPalEnvironment.live,
    currencyCode: FPayPalCurrencyCode.usd,
    action: FPayPalUserAction.payNow,
  );
Error reported in live mode：com.paypal.checkout.merchanttoken.CreateLsatTokenException: Unable to create the LSAT Token for the given Client ID

Please tell me how to solve it！！

**Comment by harrowmykel** [comment]
Please check out the troubleshooting part at the bottom of the readme

[harrowmykel/flutter_paypal_native](https://github.com/harrowmykel/flutter_paypal_native#troubleshooting-tips)
