### ISSUE TITLE
How do you set the product/item description and tax?

### ISSUE THREAD

**Issue by shingy92** [harrowmykel/flutter_paypal_native#9]
Thanks for the wonderful plugin. love it in comparison. However, tried several times to set the item description and tax to no avail. can you kindly provide a small example of setting a description and tax? Thanks

<img width="957" alt="Screenshot 2023-02-19 at 21 13 06" src="https://user-images.githubusercontent.com/27687911/219977445-d58374c9-3665-4ca4-a91a-e47209db2823.png">

**Comment by harrowmykel** [comment]
Hey, I am sorry but paypal does not provide this functionality. You can
raise an issue at PayPal SDK https://github.com/paypal/android-checkout-sdk
or you can update your UI to show this inform before the pay now.

At the moment you can only show the amount and the currency code.
